export class OutputDiemMoModel {
  idmo: number;
  objectid: number;
  sohieumo: string;
  tenmo: string;
  diadiem: string;
  loaikhoangsan: string;
  nguongocmo: string;
  tobando: string;
  dientich: number;
  truluong: number;
  chieudaytu: number;
  chieudayden: number;
  donvitruluong: string;
  donvidientich: string;
  captainguyen: string;
  dacdiem: string;
  quymo: string;
  mucdodieutra: string;
  hientrang: string;
  thanhphankhoangvat: string;
  dieukienkhaithac: string;
  geom: string;
  geovn: string;
  geowgs: string;
  hequychieu: string;
  toadox: number;
  toadoy: number;
}

export class InputDiemMoModel {
  idmo: number;
  objectid: number;
  sohieumo: string;
  tenmo: string;
  diadiem: string;
  loaikhoangsan: string;
  nguongocmo: string;
  tobando: string;
  dientich: number;
  truluong: number;
  chieudaytu: number;
  chieudayden: number;
  donvitruluong: string;
  donvidientich: string;
  captainguyen: string;
  dacdiem: string;
  quymo: string;
  mucdodieutra: string;
  hientrang: string;
  thanhphankhoangvat: string;
  dieukienkhaithac: string;
  geom: string;
  geovn: string;
  geowgs: string;
  hequychieu: string;
  toadox: number;
  toadoy: number;
}
